{config, ...}: let
  c = config.colors;
in {
  programs.btop = {
    enable = true;

    settings = {
      color_theme = "nord";
      theme_background = true;
      truecolor = true;
      force_tty = false;
      presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty";
      vim_keys = false;
      rounded_corners = true;
      graph_symbol = "braille";
      graph_symbol_cpu = "default";
      graph_symbol_mem = "default";
      graph_symbol_net = "default";
      graph_symbol_proc = "default";
      shown_boxes = "cpu mem net proc";
      update_ms = 2000;
      proc_sorting = "cpu lazy";
      proc_reversed = false;
      proc_tree = false;
      proc_colors = true;
      proc_gradient = true;
      proc_per_core = true;
      proc_mem_bytes = true;
      proc_cpu_graphs = true;
      proc_info_smaps = false;
      proc_left = false;
      proc_filter_kernel = true;
      proc_aggregate = false;
      cpu_graph_upper = "total";
      cpu_graph_lower = "total";
      cpu_invert_lower = true;
      cpu_single_graph = false;
      cpu_bottom = false;
      show_uptime = true;
      show_cpu_watts = true;
      check_temp = true;
      cpu_sensor = "Auto";
      show_coretemp = true;
      cpu_core_map = "";
      temp_scale = "celsius";
      base_10_sizes = false;
      show_cpu_freq = true;
      clock_format = "%X";
      background_update = true;
      custom_cpu_name = "";
      disks_filter = "";
      mem_graphs = true;
      mem_below_net = false;
      zfs_arc_cached = true;
      show_swap = true;
      swap_disk = true;
      show_disks = true;
      only_physical = true;
      use_fstab = false;
      zfs_hide_datasets = false;
      disk_free_priv = true;
      show_io_stat = true;
      io_mode = false;
      io_graph_combined = false;
      io_graph_speeds = "";
      net_download = 100;
      net_upload = 100;
      net_auto = true;
      net_sync = false;
      net_iface = "eth0";
      base_10_bitrate = "Auto";
      show_battery = true;
      selected_battery = "Auto";
      show_battery_watts = true;
      log_level = "WARNING";
    };

    themes.nord = ''
      theme[main_bg]="${c.black.dim}"
      theme[main_fg]="${c.white.dim}"
      theme[title]="${c.cyan.base}"
      theme[hi_fg]="${c.blue.bright}"
      theme[selected_bg]="${c.gray.base}"
      theme[selected_fg]="${c.white.bright}"
      theme[inactive_fg]="${c.gray.base}"
      theme[proc_misc]="${c.blue.bright}"
      theme[cpu_box]="${c.gray.base}"
      theme[mem_box]="${c.gray.base}"
      theme[net_box]="${c.gray.base}"
      theme[proc_box]="${c.gray.base}"
      theme[div_line]="${c.gray.base}"
      theme[temp_start]="${c.blue.base}"
      theme[temp_mid]="${c.cyan.bright}"
      theme[temp_end]="${c.white.bright}"
      theme[cpu_start]="${c.blue.base}"
      theme[cpu_mid]="${c.cyan.bright}"
      theme[cpu_end]="${c.white.bright}"
      theme[free_start]="${c.blue.base}"
      theme[free_mid]="${c.cyan.bright}"
      theme[free_end]="${c.white.bright}"
      theme[cached_start]="${c.blue.base}"
      theme[cached_mid]="${c.cyan.bright}"
      theme[cached_end]="${c.white.bright}"
      theme[available_start]="${c.blue.base}"
      theme[available_mid]="${c.cyan.bright}"
      theme[available_end]="${c.white.bright}"
      theme[used_start]="${c.blue.base}"
      theme[used_mid]="${c.cyan.bright}"
      theme[used_end]="${c.white.bright}"
      theme[download_start]="${c.blue.base}"
      theme[download_mid]="${c.cyan.bright}"
      theme[download_end]="${c.white.bright}"
      theme[upload_start]="${c.blue.base}"
      theme[upload_mid]="${c.cyan.bright}"
      theme[upload_end]="${c.white.bright}"
    '';
  };
}
