{...}: {
  imports = [
    ./bacon.nix
    ./btop.nix
    ./delta.nix
    ./emmylua.nix
    ./fd.nix
    ./fish.nix
    ./fselect.nix
    ./fzf.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./gitui.nix
    ./lolcate.nix
    ./lsd.nix
    ./misc.nix
    ./nix-init.nix
    ./pager.nix
    ./procs.nix
    ./ripgrep.nix
    ./ruff.nix
    ./ssh.nix
    ./topgrade.nix
    ./vivid.nix
    ./yamllint.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
