logfile: /var/log/cloudflared.log
metrics: 0.0.0.0:2000
no-autoupdate: true
tunnel: 8ce51aaf-f033-42aa-88b6-002af8e4dec6
credentials-file: /etc/cloudflared/8ce51aaf-f033-42aa-88b6-002af8e4dec6.json

# The `ingress` block tells cloudflared which local service to route incoming
# requests to. For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
#
# Remember, these rules route traffic from cloudflared to a local service. To route traffic
# from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
# E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.

ingress:
  - hostname: wizarr.sully.org
    service: http://localhost:5690

  - hostname: overseerr.sully.org
    service: http://localhost:5055

  - service: http_status:404
