permit root
permit keepenv persist dsully

permit nopass keepenv setenv { PATH=/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin } dsully as root cmd /home/dsully/.local/state/nix/profile/bin/nh args clean all --no-gcroots --no-direnv --optimise --keep-one --cross-filesystems
permit nopass dsully as root cmd apt-get args clean
permit nopass dsully as root cmd apt-get args update
permit nopass dsully as root cmd apt-get args dist-upgrade -y
permit nopass dsully as root cmd apt-get args autoremove -y
permit nopass dsully as root cmd /usr/bin/snap args refresh
