permit root
permit keepenv persist dsully

permit nopass dsully as root cmd apt-get args clean
permit nopass dsully as root cmd apt-get args update
permit nopass dsully as root cmd apt-get args dist-upgrade -y
permit nopass dsully as root cmd apt-get args autoremove -y
permit nopass dsully as root cmd /usr/bin/snap args refresh
