# Disable the built in GPU in favor of Nvidia.
blacklist amdgpu
blacklist nouveau

# Disable USB
blacklist btusb
blacklist bluetooth

# Prevent Bluetooth autoload
alias net-pf-31 off

# Turn of audio.
blacklist snd
blacklist snd_hda_codec
blacklist snd_hda_codec_hdmi
blacklist snd_hda_intel
blacklist snd_hwdep
blacklist snd_intel_dspcfg
blacklist snd_timer,snd_pcm
blacklist soundcore
