[global]
usershare max shares = 100
workgroup = WORKGROUP
server string = %h
multicast dns register = no
include = registry

case sensitive = true

vfs objects = catia fruit streams_xattr dirsort aio_pthread

ea support = yes
fruit:aapl = yes
fruit:encoding = native
fruit:locking = none
fruit:model = RackMac
fruit:metadata = stream
fruit:posix_rename = yes
fruit:advertise_fullsync = true
fruit:resource = xattr
fruit:veto_appledouble = no
fruit:wipe_intentionally_left_blank_rfork = yes
fruit:delete_empty_adfiles = yes
fruit:nfs_aces = no
spotlight = no

aio_pthread:aio open = yes

dns proxy = no
name resolve order = host
interfaces = eth0
bind interfaces only = yes
preferred master = no
unix extensions = no
domain master = no
server signing = no
strict locking = no
strict sync = no
use sendfile = yes
aio read size = 1
aio write size = 1

panic action = /usr/share/samba/panic-action %d

server role = standalone server
passdb backend = tdbsam
obey pam restrictions = no
unix password sync = yes
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = no
map to guest = bad user
inherit permissions = yes

load printers = no
printing = bsd
printcap name = /dev/null
disable spoolss = yes

unix extensions = no

[ai]
path = /ai
comment = AI
read only = no

[bits]
path = /bits
comment = Bits
read only = no

[home]
path = /home
comment = Home
read only = no
