PubkeyAuthentication yes
PasswordAuthentication yes
AllowAgentForwarding yes
AllowTcpForwarding yes
PrintMotd no
PermitUserEnvironment yes
StreamLocalBindUnlink yes

Subsystem       sftp    /usr/lib/openssh/sftp-server

AcceptEnv SSH_CLIENT_HOME SSH_CLIENT_MOUNT SSH_CLIENT_OS
