kernel.hung_task_timeout_secs = 0

# iotop: https://github.com/NixOS/nixpkgs/issues/160361
kernel.task_delayacct = 1

# For Neovim / inotify-watch
fs.inotify.max_user_watches=494462

# cloudflared
# https://github.com/cloudflare/cloudflared/issues/1109#issuecomment-2234239403
# https://github.com/cloudflare/cloudflared/issues/1334b
net.ipv4.ping_group_range=0 65536

# https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
net.core.rmem_max=7500000
net.core.wmem_max=7500000
