{
  lib,
  pkgs,
  my,
  ...
}: {
  home = {
    packages = with pkgs;
      [
        (lib.hiPrio uutils-coreutils-noprefix) # Rust versions of coreutils.
        _1password-cli
        act
        age
        b3sum
        bandwhich
        bombardier
        checkip
        choose
        croc
        curl
        dasel
        dua
        dust
        fclones
        gnutar
        hexyl
        inetutils
        iperf3
        ipmitool
        just
        kondo
        moor
        mtr
        p7zip
        prmt
        procs
        q
        rip2
        rnr
        rsync
        sad
        sd
        see-cat
        sniffnet
        tree
        unar
        unzip
        viu
        wget
        xcp
        xh
        xz
      ]
      ++ (with my.pkgs; [
        clean-dev-dirs
        giff
        leadr
        mdterm
        rip-go
        timecop
        xdg-open-svc
      ]);
  };
}
