{
  flake,
  pkgs,
  ...
}: {
  home = {
    packages = with (pkgs // ((flake.inputs.upstream or flake).packages.${pkgs.system} or {}));
      [
        # (hiPrio uutils-coreutils-noprefix) # Rust versions of coreutils.
        _1password-cli
        act
        age
        aichat
        b3sum
        bandwhich
        bat
        bombardier
        btop
        checkip
        chezmoi
        choose
        croc
        curl
        dasel
        delta
        direnv
        dua
        dust
        fclones
        fd
        fishPlugins.plugin-git
        fselect
        fzf
        gnutar
        gomi
        hexyl
        inetutils
        iperf3
        ipmitool
        just
        kondo
        lsd
        macchina
        moar
        mtr
        p7zip
        procs
        q
        rip2
        ripgrep
        rnr
        rsync
        sad
        sd
        see-cat
        sniffnet
        topgrade
        tree
        unar
        unzip
        viu
        wget
        xh
        xz
        zellij
        zoxide
      ]
      ++ [
        xdg-open-svc
      ];
  };
}
