name: "Build Packages and Cache"
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".github/**"
      - "Justfile"
      - "bootstrap.sh"
  schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron: "51 2 * * *"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        # For this to work, you also need to set CACHIX_AUTH_TOKEN secret in your repository secrets settings.
        cachixName:
          - dsully
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          enable_kvm: false
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        # Don't replace <YOUR_CACHIX_NAME> here!
        if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - uses: workflow/nix-shell-action@v3.4.0
        with:
          flakes-from-devshell: true
          script: |
            nix-package-updater -- --build-only --cache --force
          #script: nix run github:dsully/nix-package-updater -- --build-only --cache
