on:
  # schedule:
  #   - cron: '* * * * 0'
  workflow_dispatch:

jobs:
  update:
    name: "Update flake inputs"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          enable_kvm: false
          install_options: --no-daemon
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          commit-msg: "chore(deps): update `flake.lock`"
          git-author-email: github-actions[bot]@users.noreply.github.com
          git-author-name: Dan Sully
          git-committer-email: github-actions[bot]@users.noreply.github.com
          git-committer-name: Sully
          pr-title: "chore(deps): update `flake.lock`"
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          token: ${{ secrets.API_TOKEN }}

      # - name: Update lockfile
      #   id: update
      #   run: |
      #     cp flake.lock /tmp/oldlock
      #     nix --extra-experimental-features 'nix-command flakes repl-flake' flake update
      #     if cmp -s flake.lock /tmp/oldlock; then
      #       echo "MOD=1" >> $GITHUB_OUTPUT
      #     else
      #       echo "MOD=0" >> $GITHUB_OUTPUT
      #     fi
      # - uses: actions4git/add-commit-push@v1
      #   if: ${{ steps.update.outpus.MOD == '1' }}
      #   with:
      #     commit-message: "Update flake lockfile"
