on:
  schedule:
    - cron: "* * * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: "Update flake inputs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          enable_kvm: false
          # github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_options: --no-daemon
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        # Needed for the "gh pr merge"
        id: update-flake-lock
        with:
          commit-msg: "chore(deps): update `flake.lock`"
          # git-author-email: github-actions[bot]@users.noreply.github.com
          # git-author-name: github-actions[bot]
          # git-committer-email: github-actions[bot]@users.noreply.github.com
          # git-committer-name: github-actions[bot]
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: | # Labels to be set on the PR
            automated
            dependencies
          pr-title: "chore(deps): update `flake.lock`"

      - name: Enable Pull Request Automerge
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN }}
        run: gh pr merge --rebase --auto "${{ steps.update-flake-lock.outputs.pull-request-number }}"

